### ISSUE TITLE
Use MyLib in places that can use it

### ISSUE THREAD

**Issue by jmeaster30** [jmeaster30/SharperImage#6]
This issue is to track where we use things in the code that are implemented or should be implemented in MyLib.

- [ ] Formats/ImageLoaderHelpers (ByteSum)
- [x] Enumerators/KernelEnumerable (Floor)
- [ ] Enumerators/KernelEnumerable (Clamp)
- [x] Enumerators/*
    - I would like to have an enumerator that returns a pair of uints that go from 0,0 to width, height with controllable row major and column major orders. Then I wouldn't need to keep reimplementing the x,y index in each enumerable

**Comment by jmeaster30** [comment]
Only have ByteSum left
